### ISSUE TITLE
function blocked at DistributedDataParallel when running code at multi-machine

### ISSUE THREAD

**Issue by leoluopy** [narumiruna/pytorch-distributed-example#17]
dear author , thank you for sharing code. 
I executed the code at one single machine , using world_size 2 ,rank for 0 and 1 . It executed all well and complete the training. But when I execute the code at multi-machine ,  e.g. i used 2 machine 192.168.2.13 and 192.168.2.14 . they use the config of world_size 2 , rank 0 , and world_size 2 , rank 1. but finally the code blocked at function nn.parallel.DistributedDataParallel(model)  then time out . The training didn't start , the problem puzzled me for several days , could you please give me some advise.

**Comment by narumiruna** [comment]
Hi,

Did you use the same version of PyTorch for both machines?

**Comment by leoluopy** [comment]
> Hi,
> 
> Did you use the same version of PyTorch for both machines?


Great thanks to you for such a quick reply . and for your reminding , i just find the version of two machine is different , one is 1.1.0 another is 1.3.1. Then  i change them to same 1.3.1 version . Then I run the code again at two machine , but another problem occurs , the master node crashed at  function nn.parallel.DistributedDataParallel(model)  . the log is below:

1.3.1
Namespace(backend='nccl', batch_size=128, epochs=20, init_method='tcp://192.168.2.115:23456', learning_rate=0.001, no_cuda=False, rank=0, root='data', world_size=2)
start init nccl tcp://192.168.2.115:23456 2 0
init done 
 start model parallel
Traceback (most recent call last):
  File "main.py", line 208, in <module>
    main()
  File "main.py", line 203, in main
    run(args)
  File "main.py", line 159, in run
    model = nn.parallel.DistributedDataParallel(model)
  File "/home/leo/.pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 298, in __init__
    self.broadcast_bucket_size)
  File "/home/leo/.pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 480, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:400, unhandled system error

**Comment by leoluopy** [comment]
by using the backend of gloo my  two machine distributed training is runing well . great thanks to you . it will be greatly appreciated if you have any advice for solving the crash of using nccl backend

**Comment by leoluopy** [comment]
issue solved by adding os environment variable 
`os.environ['GLOO_SOCKET_IFNAME'] = 'enp7s0'`
` os.environ['NCCL_SOCKET_IFNAME'] = 'enp3s0'`
